# Generated by Django 4.1.7 on 2023-03-14 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("number", models.IntegerField()),
                ("complement", models.CharField(max_length=200)),
                ("postal_code", models.CharField(max_length=20)),
                ("neighborhood", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=20)),
            ],
        ),
    ]
